name = "RL_Module"
uuid = "071bb340-0fbe-4822-adfe-e5228d6bba15"
version = "0.1.0"
authors = ["Jason Eckstein <jekyllstein@gmail.com>"]

[deps]
FCANN = "8c01af00-eda8-11e9-3d27-59b8c7aa8fdd"
NVIDIALibraries = "455bb3cc-869f-42f8-aad9-fcdd684af481"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReinforcementLearning = "cab08130-57d6-4169-b7fb-99c5b62d5ad8"
TailRec = "f6209947-f0a9-4a6b-8802-d6ceac74b6f9"

[sources]
FCANN = {rev = "master", url = "https://github.com/Blackbody-Research/FCANN.jl"}
NVIDIALibraries = {rev = "master", url = "https://github.com/Blackbody-Research/NVIDIALibraries.jl"}
ReinforcementLearning = {rev = "unified-package", subdir = "ReinforcementLearning.jl", url = "https://github.com/jekyllstein/Reinforcement-Learning-Sutton-Barto-Exercise-Solutions"}
TailRec = {rev = "master", url = "https://github.com/TakekazuKATO/TailRec.jl"}

[compat]
FCANN = "1.11.0"
NVIDIALibraries = "1.0.0"
Reexport = "1.2.2"
ReinforcementLearning = "0.1.0"
TailRec = "0.2.0"
